# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b278cc7a438a6cdd51c26a7469e8042f1da78394f91b318fae4453cf4163e5d6c3cc1d1a0ea3cdf3d79046e136e581184e436b90d295eee3b7bec4863b8b8d

test:
  secret_key_base: 8dad4879d773e50c45dc59bacd6ff03529bbf3d1143f75fed558d788ece6fe6982541ad5bb64cba979f9df85eb4042238162cba5017148ac655482af3139652c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
